default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: solidus_3_development
  username:
  password:

test:
  <<: *default
  database: solidus_3_test
  username:
  password:

production:
  <<: *default
  database: solidus_3_production
  username:
  password:
